### ISSUE TITLE
Interference with automatic list continuation

### ISSUE THREAD

**Issue by bthollet** [HoBeedzc/obsidian-header-enhancer-plugin#5]
Thanx for your great plug in. I noticed an issue: when the plug in is disabled, if i am in a list and press enter, a new bullet point appears (or check-box or numbered-list item, depending the list type) and remember the identation. When the plug in is enabled and i am in a list, pressing enter would just create a new line and not add a bullet point and also forget the identation.

**Comment by HoBeedzc** [comment]
Hello @bthollet ,

Thank you for your feedback and for using my plugin. I appreciate your contribution to improving the quality of this plugin.

After conducting a thorough investigation, I can confirm the existence of the bug you mentioned. I have taken action to address this issue, and it has been successfully fixed in PR#6. The fix has been incorporated into the latest plugin release, version 0.0.5. To resolve this problem, all you need to do is update your plugin to the most recent version.

Your keen observation is invaluable in helping us maintain and enhance my plugin's functionality. We greatly appreciate your diligence in reporting this issue.

If you encounter any further problems or have additional questions while using the plugin, please don't hesitate to reach out to me at any time. I'm here to assist you and ensure a seamless experience.

Once again, thank you for your contribution and for your continued support.

Best regards,

Hobee Liu
